### PR TITLE
Rename package to `nceplibs-g2c`

### LINKED ISSUE #32: Possible name change?
### Comment:

Posing a general question here.  Is there a process for requesting a name change for a package?

Ideally, the name for this package should be nceplibs-g2c, which would be consistent with nceplibs-sp and nceplibs-ip packages.

Thanks!

### PR DESCRIPTION
**Pull request by xylar**
Keep the old name as an alias for backwards compatibility.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #32

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@EricEngle-NOAA, @ocefpaf, @timcera, @jhamman, let me know what you think.

**Review by ocefpaf — APPROVED** [review]

**Review by EricEngle-NOAA — APPROVED** [review]

**Comment by timcera** [comment]
Building locally the report at the end shows:

```
INFO :: The inputs making up the hashes for the built packages are as follows:
{
  "g2clib-1.7.0-ha770c72": {
    "recipe": {
      "channel_targets": "conda-forge main",
      "target_platform": "linux-64"
    }
  },
  "nceplibs-g2c-1.7.0-hd026740": {
    "recipe": {
      "c_compiler": "gcc",
      "c_compiler_version": "12",
      "channel_targets": "conda-forge main",
      "jasper": "4",
      "libpng": "1.6",
      "target_platform": "linux-64",
      "zlib": "1.2"
    }
  }
}

```
Should the contents of "recipe" for both g2clib and nceplibs-g2c be identical?

**Comment by xylar** [comment]
@timcera, thanks for having a look!

> Should the contents of "recipe" for both g2clib and nceplibs-g2c be identical?

No, I don't think so.  I think `g2clib` has `nceplibs-g2c` as its only dependency so I think it's correct that no dependencies show up in "recipe". @ocefpaf, please correct me if I'm wrong.

**Comment by timcera** [comment]
I just extracted the g2clib package and it just points to nceplibs-ip.  So, that's really cool.

**Review by timcera — APPROVED** [review]

**Comment by xylar** [comment]
I don't know how active you are on conda-forge @jhamman.  I think 3 approvals is probably good enough, but your comments are welcome!

**Comment by xylar** [comment]
@EricEngle-NOAA, thanks for the suggestion and thanks everyone for having a look!

**Pull request merged**
