### PR TITLE
Manual architecture migration

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Review by ocefpaf — APPROVED** [review]

**Comment by xylar** [comment]
@ocefpaf and @jhamman, my experience with architecture migration is pretty limited so any advice you have would be welcome.  The tests passed before I rebased, for what it's worth.

**Comment by ocefpaf** [comment]
> my experience with architecture migration is pretty limited so any advice you have would be welcome.

Same here  :smile: 

> The tests passed before I rebased, for what it's worth.

They are passing and that is good enough for me. Do you want to merge?

**Comment by xylar** [comment]
Great, well we'll learn about architecture migration (slowly) together...

Merging!

**Pull request merged**
