### PR TITLE
Update to 1.6.3

### PR DESCRIPTION
**Pull request by xylar**
Add xylar as a maintainer

Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@jhamman and @ocefpaf, this seems overdue for an update.  Also, I think it would need to be rebuilt for other architectures for downstream packages to be able to migrate.  Please merge if you're okay with the updates.

**Comment by xylar** [comment]
Thanks @ocefpaf!

**Comment by ocefpaf** [comment]
> Thanks @ocefpaf!

Thank you for taking care of this package!

**Pull request merged**
